### ISSUE TITLE
Need help loading script with tampermonkey

### ISSUE THREAD

**Issue by KilliCopps** [alexbr/movescount-batch-exporter#2]
Hi there, I'm sure this is the most basic of basic but I'd really like to use this script to export data from Movescount but am not so clued up on how it all works. I added tampermonkey to my google chrome browser, copied your exporter.js script and pasted it into a new script file (if thats what you call it) in tampermonkey. I then saved it and enabled it and it shows up in my "installed userscripts" tab in tampermonkey. 
![image](https://cloud.githubusercontent.com/assets/19300650/15172851/ccc5212c-1758-11e6-91cd-4e6f3a5a9f27.png)

![image](https://cloud.githubusercontent.com/assets/19300650/15172891/09af7b96-1759-11e6-87c7-940a4c7f5717.png)

But in movescount the options for export don't show up when I hover on the "tools" dropdown on the movescount summary page. 
![image](https://cloud.githubusercontent.com/assets/19300650/15172779/61052a2c-1758-11e6-9ecc-603d783d9ec5.png)

If you have some more detailed instructions on how to load the script or an idea of where I went wrong I'd really appreciate the help.
Thanks,
Killi

**Comment by alexbr** [comment]
Without any investigation... my guess is that Movescount updated the site since I created this script. I'll try to update it as soon as I can.

**Comment by alexbr** [comment]
I just tested on chrome and it worked for me. It doesn't look like tampermonkey is loading the script on the movescount site for you. What is that extra header you have in the script? Tampermonkey default cruft? Delete from the first `// ==Userscript==` to `// ==Userscript==` on line 15, that's not part of my script and most likely what's causing the problem.

**Comment by KilliCopps** [comment]
Thank you so much for the help. I tried deleting the extra lines of code
and this error pops up when I hit save
[image: Inline images 1]
I tried it anyway and still no luck. Do I need to do something else in
tampermonkey other than enable the script? Should I be starting the script
from "function exportMoves(format) {" ? Sorry for being so clueless!

**Comment by alexbr** [comment]
Delete that script and add a new one. I added instructions to the Readme.md

**Comment by KilliCopps** [comment]
This is working great now, thanks so much for the help. I only actually got it to work today for some reason - tampermonkey popped up and asked if I wanted to upgrade the movescount exporter script just now and since then it's been working. Really awesome, thanks again
