### ISSUE TITLE
Tools dropdown missing

### ISSUE THREAD

**Issue by shmish** [alexbr/movescount-batch-exporter#3]
It doesn't look like Movescount has a Tools dropdown.  I'm only seeing Training Load, Rest and Recovery, Free Compare, and Moves.

**Comment by alexbr** [comment]
Yeah, looks like they removed it once you select 'multiple' on the moves summary screen. I'll see what I can do to 're-enable' it.

**Comment by groie** [comment]
Any news on this?

**Comment by alexbr** [comment]
No, I never got a chance to look at it then forgot. Thanks for the reminder :)

**Comment by elenadmitrieva** [comment]
One more reminder =)

**Comment by Donaldini** [comment]
And another :D

**Comment by jeusdi** [comment]
Knocking on the door...

**Comment by ardoi** [comment]
Added a PR (#4) that makes the exporter links appear.

**Comment by Davidoff80** [comment]
I still don't see the dropdown. Is it disappeared again? I tried both Chrome and Firefox.

I do get a lot of XHR-errors in the console, but I get them with or without the JS:
Failed to load http://mc-realtime-prod.eu-west-1.elasticbeanstalk.com/socket.io/?EIO=3&transport=polling&t=LzTFYsp: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://www.movescount.com' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
